[package]
name = "my-strategy"
version = "0.1.0"
edition = "2018"

[dependencies]
log = "0.4.6"
env_logger = "0.6.0"
serde = "1"
serde_json = "1"
serde_derive = "1"

[[bin]]
name = "repeater"
edition = "2018"
path = "src/repeater.rs"
